"""
Figure: Fixed-Effect Coefficient Plots (Dot-and-Whisker)
========================================================
Generates per-layer coefficient plots showing significant predictors
(p < .05) across programs, with separate panels for CA, LEQ, and IL.

Input: CSV with columns [variable, coef, ci_lower, ci_upper, pval, program]
       Generated by 02_gpa_lmm.py (one file per program).

Usage:
    python figures/fig_coefficients.py --input results/merged_coefficients.csv
"""

import os, argparse
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

mpl.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
    "font.size": 11,
})

# Colorblind-friendly palette with distinct markers
PROGRAM_STYLE = {
    "program_1": {"color": "#1F77B4", "marker": "o"},
    "program_2": {"color": "#D67228", "marker": "s"},
    "program_3": {"color": "#2CA02C", "marker": "^"},
    "program_4": {"color": "#9467BD", "marker": "v"},
    "program_5": {"color": "#BCBD22", "marker": "D"},
    "program_6": {"color": "#17BECF", "marker": "H"},
    "program_7": {"color": "#D62728", "marker": "p"},
}

# Assign variables to layers — adapt to your own variable names
LAYER_MAP = {
    # CA
    "DFW Rate": "CA", "Delay": "CA", "Blocking Factor": "CA",
    "Number of Units": "CA", "Time to Degree": "CA",
    # LEQ
    "Lecture Clarity": "LEQ", "Lecturer Helpfulness": "LEQ",
    "Interest Stimulation": "LEQ", "Recitation Clarity": "LEQ",
    "Recitation Support": "LEQ", "Instructor Mastery": "LEQ",
    "Recitation Quality": "LEQ", "Course Comparison": "LEQ",
    "Homework Value": "LEQ", "Reading Value": "LEQ",
    "Study Hours": "LEQ",
    # IL
    "Ethnicity_Asian": "IL", "Ethnicity_Black": "IL",
    "Ethnicity_Hispanic": "IL", "Ethnicity_International": "IL",
    "Male": "IL", "First-Generation": "IL", "Pre-College Credits": "IL",
}


def plot_layer(df, layer, outdir):
    sig = df[(df["layer"] == layer) & (df["pval"] < 0.05)]
    if sig.empty:
        return

    # Separate DFW for CA (different scale)
    is_dfw = sig["label"].str.contains("DFW", case=False)
    has_dfw = layer == "CA" and is_dfw.any()
    main = sig[~is_dfw] if has_dfw else sig
    dfw = sig[is_dfw] if has_dfw else None

    for subset, suffix in [(main, ""), (dfw, "_DFW_zoom")]:
        if subset is None or subset.empty:
            continue

        ordered = (subset.assign(abs_c=subset["coef"].abs())
                   .groupby("label")["abs_c"].mean()
                   .sort_values(ascending=False).index.tolist())
        y_map = {v: i for i, v in enumerate(ordered)}
        progs = sorted(subset["program"].unique(),
                       key=lambda p: list(PROGRAM_STYLE).index(p) if p in PROGRAM_STYLE else 99)
        offsets = np.linspace(-0.30, 0.30, len(progs))

        fig_h = max(4, 0.6 * len(ordered) + 2)
        fig, ax = plt.subplots(figsize=(10.5, fig_h))

        for i, p in enumerate(progs):
            s = PROGRAM_STYLE.get(p, {"color": "gray", "marker": "o"})
            g = subset[subset["program"] == p]
            for _, r in g.iterrows():
                y = y_map[r["label"]] + offsets[i]
                ax.errorbar(r["coef"], y,
                            xerr=[[r["coef"]-r["ci_lower"]], [r["ci_upper"]-r["coef"]]],
                            fmt="none", capsize=5, color=s["color"], alpha=0.7, zorder=2)
                ax.scatter(r["coef"], y, marker=s["marker"], s=80,
                           facecolors=s["color"], edgecolors="black", linewidths=0.7, zorder=4)

        ax.axvline(0, color="#2C3E50", linewidth=1.5, alpha=0.7)
        ax.set_yticks(range(len(ordered)))
        ax.set_yticklabels(ordered, fontweight="bold")
        ax.set_xlabel("Coefficient Estimate (GPA points)", fontweight="bold")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        handles = [Line2D([0],[0], marker=PROGRAM_STYLE[p]["marker"], color="w",
                          markerfacecolor=PROGRAM_STYLE[p]["color"],
                          markeredgecolor="black", markersize=9, label=p) for p in progs]
        fig.legend(handles=handles, loc="lower center", ncol=len(progs),
                   bbox_to_anchor=(0.5, 0), frameon=True)
        plt.tight_layout(rect=(0, 0.08, 1, 1))

        fname = f"fig_{layer}_coefficients{suffix}"
        for ext in ["png", "pdf"]:
            fig.savefig(os.path.join(outdir, f"{fname}.{ext}"),
                        dpi=600, bbox_inches="tight", transparent=True)
        plt.close(fig)
        print(f"  ✓ {fname}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="results/merged_coefficients.csv")
    args = parser.parse_args()

    outdir = os.path.join("results", "figures")
    os.makedirs(outdir, exist_ok=True)

    df = pd.read_csv(args.input)
    df = df[~df["variable"].str.contains("Intercept|Group|Var", case=False, na=False)]

    # Users: map your raw variable names to display labels here
    df["label"] = df["variable"]  # Replace with your mapping if needed
    df["layer"] = df["label"].map(LAYER_MAP).fillna("Other")

    for layer in ["CA", "LEQ", "IL"]:
        plot_layer(df, layer, outdir)
